export const GET_PRODUCTS = 'GET_CONTACTS';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const LOAD_NEXT_PAGE = 'LOAD_NEXT_PAGE';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILD = 'REGISTER_FAILD';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_BACKGROUND = 'SET_BACKGROUND';
export const CLEAR_BACKGROUND = 'CLEAR_BACKGROUND';